### ISSUE TITLE
example in readme fails: /usr/lib/libc.dylib: error: unrecognized file type

### ISSUE THREAD

**Issue by timotheecour** [andreiw/tinycc#1]
```
 ./tcc -B. -I./include -I. -I.. -D_ANSI_SOURCE -run examples/ex1.c
/usr/lib/libc.dylib: error: unrecognized file type
tcc: error: library 'c' not found
```
I'm on OSX 10.13.3

**Comment by c-blake** [comment]
From the current mob branch, after a ``./configure && make && sudo make install`` on OSX 10.13.2, ``cd examples; tcc -run ex1.c`` works as expected for me.  ``tcc -c`` still only produces ELF objects (not requisite Mach-O) on this branch and mob, though.  So, not really usable as a general purpose compiler.

**Comment by andreiw** [comment]
I don't think I've ever said tcc could be used a general-purpose compiler on OSX.

You're welcome to contribute Mach-O support (but not to me, to the tcc mob branch)

**Comment by mgttt** [comment]
as a shortcut maybe we can write a tcc_elf2mac() with logic from:

https://github.com/vertis/objconv/
https://github.com/vertis/objconv/blob/master/src/elf2mac.cpp
